//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sample
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillItem
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public string SessionKey { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int Quantity { get; set; }
        public decimal Rate { get; set; }
        public string InvoiceNumber { get; set; }
        public string Imagepath { get; set; }
        public string CustomerName { get; set; }
    }
}
