//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Subcategories = new HashSet<Subcategory>();
        }
    
        public int Id { get; set; }
        public string CategoryName { get; set; }
        public int PoductId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ICollection<Subcategory> Subcategories { get; set; }
    }
}
