//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sample
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportBill
    {
        public int Id { get; set; }
        public decimal TransportBill1 { get; set; }
        public string SessionKey { get; set; }
        public System.DateTime EventDate { get; set; }
        public System.DateTime SetupDate { get; set; }
        public string DeliveryAddress { get; set; }
    }
}
